name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Docker Hub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build & Push Docker image
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest

      # Step 4: Deploy to EC2
      - name: Deploy via SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest &&
            sudo docker stop my-node-app || true &&
            sudo docker rm my-node-app || true &&
            sudo docker run -d -p 80:3000 --name my-node-app ${{ secrets.DOCKER_USERNAME }}/my-node-app:latest
          "
